Disabled 'Running...' button while query running
forcedotcom/soql-tooling pull request #106
Opened 2020-12-16 19:12 UTC by jgellin-sf

### What does this PR do?
This PR provides the SOQL Builder UI-side function for indication that a query is running. When the `Run Query` button is pressed, the button is transformed into a disabled `Running...` button, and remains so until VSCode sends the `run_query_done` message.
![runquery](https://user-images.githubusercontent.com/55159130/102395065-a5951a80-3fa8-11eb-8b59-8e73e86c4f36.gif)

### What issues does this PR fix or reference?
@W-8207738@

2020-12-16 20:03 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/app/app.test.ts
> +import { ArgumentOutOfRangeError, BehaviorSubject, Observable } from 'rxjs';
Is this one of those sneaky IDE imports?

2020-12-16 20:11 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/toolingSDK.test.ts
> +    expect(runStateObserver.mock.calls.length).toBe(2);
Is this 2 because behavior subject gets an immediate callback with the current value?

2020-12-16 20:20 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/message/standaloneMessageService.ts
> +    if (messageObj.type === MessageType.RUN_SOQL_QUERY) {
we actually do the full round trip across an iframe using this development repo that behaves like vscode.  So you can just recieve the message there and respond using a timeout.

https://github.com/forcedotcom/soql-tooling-standalone/blob/main/src/client/modules/my/app/app.ts#L23

2020-12-16 20:21 UTC, dehru requested changes
This UX has bugged me since the start.  Great to get this in.  I had one comment about the setTimeout to mock the response.  Let's move that to the standalone server repo.  So you can literally just remove that whole mocking of the response from this PR.

2020-12-16 21:09 UTC, jonnyhork reviewed
Looks good for the most part, nice and simple. Just a few comments on the CSS and how we want to approach JS/CSS overall in the UI.

2020-12-16 21:09 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
Another way to do this without two templates is by making the text of the button dynamic like we do with the [fields](https://github.com/forcedotcom/soql-tooling/blob/f611867098c2fbe360b80967016d8039ebd8e8f7/packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts#L65) throughout the UI.
```javascript
    return this.isLoading ? 'Loading...' : 'Select Field...';
```

In this case, if we did not use the templates, the classes and the disabled would require some JS and I think would be more work without that much benefit other than consistency I guess.

I do not see the class `running-button` in the CSS though are you still using it? 
I probably would have used a different class name than `run-button` if I did this again, I'm trying out this whole [BEM](https://css-tricks.com/bem-101/) thing for new work.
For example:
```CSS
header__button--run /* or ready, enabled */
header__button--running /* disabled */

header__button-run--enabled
header__button-run--disabled
```

I am still getting used to it but the idea is to be consistant and predictable with our class names.

2020-12-16 21:20 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/app/app.test.ts
> +import { ArgumentOutOfRangeError, BehaviorSubject, Observable } from 'rxjs';
Yup. Removed with `remove unused import` commit.

2020-12-16 21:20 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/toolingSDK.test.ts
> +    expect(runStateObserver.mock.calls.length).toBe(2);
Yes

2020-12-16 21:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
Actually for BEM naming I don't think we include the `header` part... but same idea

2020-12-16 21:32 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/message/standaloneMessageService.ts
> +    if (messageObj.type === MessageType.RUN_SOQL_QUERY) {
Ah cool. I've moved it to the tool in this https://github.com/forcedotcom/soql-tooling-standalone/pull/3 and removed from this PR with the `Move standalone run query response to standalone tool` commit.

2020-12-16 21:41 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
It turns out I wasn't styling `run-button` or `running-button` so I've removed those from the template in the `Remove un-styled classes` commit.

2020-12-16 21:53 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
> +}
For the sake of JS ease of use, I think it's probably better to handle disabled button just using CSS as you have done rather than with the attribute. Then it's treated as just another class and not this special case.

I agree it shoud be handled consistently in the CSS common. I see in the where branch the CSS def is in `where.css`. Maybe you can move it to CSS common and we can merge the WHERE stuff, then I'll change to that class when I rebase.

2020-12-16 22:01 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
Whoops acted too fast. `run-button` is used in the test code. Restored now.

2020-12-16 22:09 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
> +}
ok, well my branch is already merged to `feature/where` but I can create a new PR to move the class to CSS Common, is that what you were thinking?

2020-12-16 22:18 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
> +}
Yeah that sounds good.

2020-12-16 23:36 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
> +}
@jgellin-sf I created and merged #108 to the `feature/where` for your pleasure.

2020-12-21 16:53 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
That's relevant as we have discussed moving away ( slowly ) from using css classes as selectors in testing code, because it's often not apparent that the class is for testing vs styling.

2020-12-21 17:15 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/header/header.html
> +        <button class="running-button" disabled>Running...</button>
I agree with moving that direction

2021-01-04 20:40 UTC, dehru approved these changes

2021-01-04 20:53 UTC, merged