Jhork/custom select fields
forcedotcom/soql-tooling pull request #111
Opened 2020-12-23 23:50 UTC by jonnyhork

### What does this PR do?
Use a custom select component in the SELECT from of the SOQL Builder.
### What issues does this PR fix or reference?

2020-12-31 00:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.html
> +      <p class="option option--placeholder">No results found.</p>
@ekapner This text will be displayed to the user when they type in a search term and there are no results. I used the same phrase as VS Code when you search you code base.
Please see the gif in the description for an example.

2020-12-31 00:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/fields/fields.ts
> +  selectPlaceHolderText = 'Search fields...'; // TODO: i18n
@ekapner The default select elements say `Select fields...` so I just changed it to `Search fields...` to indicate they can type to search.

2020-12-31 00:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  }
This is used to control whether the component responds to some keyboard events like arrow navigation.
**If**
- the options list is visible
- there are options to choose from
- There are results of a user search

**then allow keyboard navigation**
It reads a bit odd but the names of the variables make more sense for how they are used in other cases. 

`!!(!this.optionListIsHidden && this.optionList.length)` would return the number value of the length without the double bang, I thought it makes more sense to have a boolean value returned.

2020-12-31 00:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  getAvailableOptions() {
Sets the available options in state.

available options = `all options - selected options` case insensitive

2020-12-31 00:23 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  }
This is used to render the option placeholder template "No results found." when there is no match to the user search.

2020-12-31 16:38 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  originalUserInput = '';
`originalUserInput` is used as a cache for what is typed into the input element, if the user types "na" and then navigates down to a the list of options to "name" the search term becomes "name". 
Then if they navigate back up to the search bar the value becomes "na" again or whatever they typed initially.

2020-12-31 16:42 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +      this.filterOptionsBySearchTerm();
If there is already some text in the search bar and they click on it to see the options list again, it will resemble those that match the search term. 
Otherwise it will be all available options.

2021-01-04 16:21 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    document.addEventListener('click', () => {
We need to adjust this a bit so that we can also call document.removeEventListener on the disconnectedCallback.

https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.create_lifecycle_hooks_dom

2021-01-04 16:21 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    this.optionsWrapper = this.template.querySelector('.options__wrapper');
We should check to see if this is already set, before we query again since renderedCallback can happen more than once.

2021-01-04 16:24 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  getAvailableOptions() {
Semantically, this function behaves more like `calculateAvailableOptions` since the work "get" makes me think it should return something.

2021-01-04 16:26 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  haveOptionsToNavigate(): boolean {
usually, then verb _tense_ i see here is `hasOptionsToNavigate`

2021-01-04 16:32 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +      this.optionList[position].scrollIntoView({
so nice.

2021-01-04 16:33 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +          optionValue
let's just simplify this to `value`

2021-01-04 16:34 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/fields/fields.ts
> +        detail: { field: e.detail.optionValue }
as noted above, seems like `value` is simpler.

2021-01-04 16:36 UTC, dehru requested changes
I've got a couple minor comments.  Most are just opinions about naming or stylistic suggestions.  The one we do need to handle though is the `disconnectedCallback` so we can unregister the document click listener.

2021-01-04 16:39 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.test.ts
> +    it('should reset the search bar when X is clicked', () => {
This test is fantastic.

2021-01-04 16:45 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.test.ts
> +/*
It'd be good to assign all the duplicated class names and such to variables inside the outer `describe` section to prevent duplication.  Like `searchBarSelector = 'input[name=search-bar]'`, or maybe write a couple functions to get those for you each time.

2021-01-09 03:22 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    document.addEventListener('click', () => {
disconnectedCallback added

2021-01-09 03:23 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    this.optionsWrapper = this.template.querySelector('.options__wrapper');
cached and used if set

2021-01-09 03:24 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  haveOptionsToNavigate(): boolean {
updated

2021-01-09 03:24 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +          optionValue
done

2021-01-09 03:24 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.test.ts
> +/*
Done

2021-01-09 03:25 UTC, dehru approved these changes

2021-01-09 03:26 UTC, dehru commented
Let's push this into a feature/custom-select and continue to implement this for the rest of the fields.  This is so cool that i can't face another standard select dropdown.

2021-01-14 17:59 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/app/app.ts
> +          ? sobjectMetadata.fields.map((f) => f.name).sort()
Let's sort the fields alphabetically;  I wanted to do it here so that the custom-select component doesn't do any sorting and displays the fields in the order it was given.  It shows it's options in the order given.

2021-01-14 18:03 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.css
> +*/
I was able to fix this by removing attributes.  I just lucked out.  https://github.com/forcedotcom/soql-tooling/pull/111/commits/f27d36a10ca783d07e211788092828ad276de753

<img width="508" alt="Screen Shot 2021-01-14 at 11 00 29 AM" src="https://user-images.githubusercontent.com/599418/104630274-d2942600-5657-11eb-8fda-9168886023e6.png">

<img width="515" alt="Screen Shot 2021-01-14 at 11 02 50 AM" src="https://user-images.githubusercontent.com/599418/104630516-125b0d80-5658-11eb-80e3-d69c7b63f784.png">

2021-01-14 18:05 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    );
I simplified this for readability.  It was a series of `!!(! condition & condition) & !condition)` and I personally was struggling to read it.

2021-01-14 18:08 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +    this.openOptionsMenu();
I moved this `openOptionsMenu()` to the bottom.  For some reason, if I matched a search term like "Id" but didn't click away from the input box, just kept typing with another search term, this previously selected search term would remain in the options list.  By waiting until last to display it, LWC seems to render the option list correctly.

2021-01-14 18:26 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  }
I struggled comprehending this and updated it for readability.

2021-01-14 18:26 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.ts
> +  getAvailableOptions() {
I updated this.

2021-01-14 18:27 UTC, merged