Support IN, NOT IN, INCLUDES, EXCLUDE operators
forcedotcom/soql-tooling pull request #123
Opened 2021-01-21 20:15 UTC by jgellin-sf

### What does this PR do?
This PR adds SOQL Builder support for IN, NOT IN, INCLUDES, and EXCLUDES operators. 
- WHERE clauses containing conditions with these operators are no longer unsupported in the SOQL model
- The operators are added to the SOQL Builder UI
- The operators have specific validation, in which the input string is split by comma into separate values, which are then each validated by type

When a multi-value operator is selected, the input must be a comma-separated list of values. The values are not manipulated or normalized as with other operators, so strings must be surrounded by single quotes.

### What issues does this PR fix or reference?
@W-8675683@

2021-01-26 19:21 UTC, jgellin-sf commented on packages/soql-model/src/messages/messages.ts
> +
@ekapner A few new messages

2021-01-27 19:55 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
> +    modelValue: undefined
Why undefined here?

2021-01-27 19:56 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.test.ts
> +          },
what's the reasoning for this change?

2021-01-27 20:03 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +              : CONDITION_TYPE_NONE
head spinning.  i see what you are doing with these ternaries.  I which there was a better way to do this by flipping the data structure so you could just do `Soql.CompareOperator[uiModelCondition.operator]`

2021-01-27 20:20 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
> +    modelValue: undefined
The parser (and resulting soql-model) is not as tidy as the field-operator-value trifecta of the UI. Simple comparisons (=, !=, <, >, <=, >=) have values that are parsed as literals. LIKE conditions are parsed differently because like values have those `%` wildcards. Similarly the multi-value operators are parsed differently. Also, IN can take an nested inner query as a value. For these reasons we end up with different condition objects for different operators: FieldCompareCondition, LikeCondition, InListCondition, IncludesCondition. FieldCompareCondition has an operator field which can be one of the simple operators. InListCondition can have IN and NOT IN. IncludesCondition can have INCLUDES or EXCLUDES. LikeCondition has only one possible operator (LIKE) so there is no operator field. Hence the 'undefined'. The way it works logically is if the operator is undefined we know it's a LIKE condition. Is this ugly? Yes.

Now. It's not like we are stuck with this. It's our model we can do whatever we want. Maybe we add an operator to the LikeCondition model. It's only ever going to have the LikeOperator.LIKE value, but makes this code a little nicer. What do you think?

2021-01-27 20:25 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.test.ts
> +          },
Because these multi-value operators don't conform to the previous single field-single operator-single value assumption, we switch from using the ad hoc UI model to the actual soql-model object. This condition object is the same JSON as `new Impl.FieldCompareConditionImpl(new Impl.FieldRefImpl('Name'), Soql.CompareOperator.EQ, new Impl.LiteralImpl(Soql.LiteralType.String, "'pwt'")`.

2021-01-27 20:31 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +              : CONDITION_TYPE_NONE
Between this and the `undefined` comment above I have some changes in mind for soql-model to make it work for us a little better for us. Stay tuned...

2021-01-27 21:14 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
> +    modelValue: undefined
Yeah, i think it would cause me a little less mental sandpaper to see something there.

2021-01-27 22:39 UTC, ekapner commented on packages/soql-model/src/messages/messages.ts
> +  export const error_incompleteMultiValueList = 'Incomplete values list. Values must be in parentheses and separated by commas.'
```suggestion
  export const error_incompleteMultiValueList = 'Incomplete values list. Place values in parentheses, separated by commas.'
```

2021-01-27 22:40 UTC, ekapner commented on packages/soql-model/src/messages/messages.ts
> +  export const error_fieldInput_string = 'Value must be enclosed in single quotes';
```suggestion
  export const error_fieldInput_string = 'Enclose value in single quotes';
```

2021-01-27 23:14 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +              : CONDITION_TYPE_NONE
I second the head spinning part

2021-01-27 23:46 UTC, jonnyhork reviewed
Wow, there is a lot here to digest!

2021-01-27 23:46 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +  // }
Not sure if this is still WIP but I wanted to check to see if this commented out code should be here?

2021-01-28 14:27 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
> +    modelValue: undefined
I reworked the condition model to make this code a little less squishy. See the `Refactor condition model to simplify code` commit.

2021-01-28 14:27 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +              : CONDITION_TYPE_NONE
This code is simpler after refactoring the condition model a bit. See the `Refactor condition model to simplify code` commit.

2021-01-28 14:29 UTC, jgellin-sf commented
@ekapner Thanks for the review. Your suggestions are committed.

2021-01-28 16:06 UTC, jonnyhork commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +      switch (uiModelCondition.operator) {
nice, this looks much cleaner!

2021-01-28 16:19 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +      enum ConditionType {
would it make sense to define these outside of this soqlUtils function?  Is it usable elsewhere?

2021-01-28 16:23 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +        this._criteriaDisplayValue = condition.values.map(value => value.value).reduce((soFar, next) => {
Array.join() is a simpler implementation here that might work.
`condition.values.map(value => value.value).join(', ');`

2021-01-28 16:24 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
> +      enum ConditionType {
Basically it only exists to tell us what kind of model object to create from a non-model object, so it might only apply here.  I don't know where else we'd use it.

2021-01-28 16:26 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +  getFieldName(): string | undefined {
Can you replace this with optional chaining?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

2021-01-28 16:40 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/where/where.ts
> +  condition: any;
Can this be a JsonMap instead of any?

2021-01-28 16:50 UTC, dehru commented
I think the whereModifierGroup.test.ts file should include a test for the new multipleValueOperator to verify, even though that logic is exported from soqlUtils.ts.  Just something minor and quick.  And additionally, validating the `modifiergroupselection ` event sends the right condition.

2021-01-28 16:54 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +        this._criteriaDisplayValue = condition.values.map(value => value.value).reduce((soFar, next) => {
Updated

2021-01-28 16:55 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +  getFieldName(): string | undefined {
Webpack doesn't seem to be able to handle optional chaining.

2021-01-28 16:55 UTC, jgellin-sf commented on packages/soql-builder-ui/src/modules/querybuilder/where/where.ts
> +  condition: any;
Yup. Done

2021-01-28 17:02 UTC, jgellin-sf commented
@dehru 
![image](https://user-images.githubusercontent.com/55159130/106172259-9c2ece80-6160-11eb-8f87-3fc34522dfe7.png)

See `Add test for multi-value operator` commit

2021-01-28 17:08 UTC, dehru requested changes
This could be operator error.  But i'm getting a validation operator error with includes/excludes.  See movie.
https://user-images.githubusercontent.com/599418/106172921-97621e80-6150-11eb-8374-8b2620ad28d2.mov

And an issue converting where in from text editor into builder whereModifierGroup display.


https://user-images.githubusercontent.com/599418/106173005-b06acf80-6150-11eb-8776-a03b0d7cbe49.mov

2021-01-28 17:25 UTC, jgellin-sf commented
@dehru Should be fixed.

2021-01-28 19:54 UTC, dehru commented on packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts
> +  getFieldName(): string | undefined {
oh yeah, i remember that now.

2021-01-28 19:58 UTC, dehru commented on packages/soql-model/src/model/model.ts
> +  // field [In|NotIn] ( semi-join ) => UnmodeledSyntax
So is this just a way to document that a field that is a semi-join with In, NotIn syntax, is currently unmodeled?  I remember you showing this before in the walkthrough...but can't remember the specifics

2021-01-28 20:01 UTC, dehru commented on packages/soql-model/src/validators/validatorFactory.test.ts
> +      'MultipleInputValidator',
will these every change to something else based on field type?

2021-01-28 20:02 UTC, dehru approved these changes

2021-01-28 20:13 UTC, merged