build: script to update internal dependency versions
forcedotcom/soql-tooling pull request #204
Opened 2021-02-22 21:58 UTC by dobladez

Release-As: 0.1.0

### What does this PR do?
Force version number for first release of soql-common.
Also: script to update version of internal dependencies in the monorepo

2021-02-22 22:13 UTC, jgellin-sf requested changes
Couple of typos

2021-02-22 22:13 UTC, jgellin-sf commented on .github/workflows/release-soql-common.yml
> +           git commit -a -m "chore: bump soql-common version dependents to $SOQL_MODEL_VERSION"
Should this be `$SOQL_COMMON_VERSION`?

2021-02-22 22:13 UTC, jgellin-sf commented on scripts/update-interdependency-versions.js
> +            `updated ${packageName} dependency version on ${pacakgeFile}`
TYPO
`pacakgeFile` -> `packageFile`

2021-02-23 20:34 UTC, closed without merging

2021-02-23 20:34 UTC, dobladez commented
Superseded by https://github.com/forcedotcom/soql-tooling/pull/208